### ISSUE TITLE
Detailed Instruction?

### ISSUE THREAD

**Issue by nalzok** [IndieRunner/IndieRunner#4]
Is there any instruction on running a game with IndieRunner? It can be a README file, a blog post, a screencast, or anything. I just want to know what command I should execute to run, let's say, Brotato.

**Comment by rfht** [comment]
Please note that this is still pre-release state (could probably call it beta stage).

The Makefile.PL installation isn't set up yet, so right now you have to clone the git repo and install the dependencies (most should be listed in https://github.com/IndieRunner/IndieRunner/blob/main/README.md).

Launching a game with it is mainly done by calling `script/indierunner` from the game's location. It uses heuristics to try to figure out the game engine and the main game file to call. It may also rename some bundled libraries that prevent execution. With Brotato:

```
$ cd /path/to/Brotato # location of Brotato.pck
$ /path/to/IndieRunner/script/indierunner
```

You can use `-h` to get a list of flags.

**Comment by rfht** [comment]
there will eventually be a port on OpenBSD that will make installation painless.

**Comment by rfht** [comment]
There is now a port on OpenBSD so I'm closing this issue. If questions come up, please open a new issue.
